name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

  # Also trigger on PR comments that mention Claude
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Run on PR events OR when Claude is mentioned in a PR comment
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       (contains(github.event.comment.body, '@claude') ||
        contains(github.event.comment.body, '@Claude') ||
        contains(github.event.comment.body, '@CLAUDE')))

    # Optional: Additional filters by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Get PR details when triggered by comment
        if: github.event_name == 'issue_comment'
        id: pr-details
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          PR_DATA=$(gh api "/repos/${{ github.repository }}/pulls/${PR_NUMBER}")
          echo "head_sha=$(echo "$PR_DATA" | jq -r '.head.sha')" >> $GITHUB_OUTPUT
          echo "head_ref=$(echo "$PR_DATA" | jq -r '.head.ref')" >> $GITHUB_OUTPUT
          echo "base_ref=$(echo "$PR_DATA" | jq -r '.base.ref')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set PR SHA
        id: pr-sha
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "sha=${{ steps.pr-details.outputs.head_sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ steps.pr-sha.outputs.sha }}

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
            PR SHA: ${{ steps.pr-sha.outputs.sha }}
            EVENT TYPE: ${{ github.event_name }}

            # Context
            ${{ github.event_name == 'issue_comment' && format('This workflow was triggered by a comment mentioning Claude (in any case variation): "{0}"', github.event.comment.body) || 'This is a regular PR review triggered by PR changes.' }}

            IMPORTANT: Comment Management Strategy

            There are TWO types of comments you may create:

            1. **SUMMARY REVIEW COMMENT** (only ONE per PR):
               - This is the main code review summary
               - Always starts with "## Claude Code Review Summary"
               - Gets UPDATED/EDITED on each new push (never create duplicates)
               - Contains overall PR feedback on code quality, security, performance, etc.

            2. **REPLY COMMENTS** (multiple allowed):
               - These are responses to user comments that mention Claude (case-insensitive: @claude, @Claude, claude, CLAUDE, etc.)
               - Create a NEW comment each time (don't edit)
               - Reference the comment you're responding to
               - Be helpful and specific to the question asked

            # Instructions based on trigger type:

            ${{ github.event_name == 'pull_request' && 'PULL REQUEST EVENT - Update or create the SUMMARY comment:' || 'COMMENT EVENT - Create a REPLY:' }}

            ## For Pull Request Events (opened/synchronize):

            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Use the repository's CLAUDE.md for guidance on style and conventions.

            IMPORTANT FORMATTING GUIDELINES:

            1. **BREVITY IS KEY**: Keep the main summary concise and scannable. Get to the point quickly.
            2. **Use collapsible sections liberally**: Whenever you have detailed explanations, code examples, or extended analysis, wrap them in GitHub's `<details>` tags:
               ```markdown
               <details>
               <summary>Performance optimization details</summary>

               Detailed analysis, code examples, benchmarks, etc...

               </details>
               ```
            3. **Structure for quick scanning**:
               - Start with a brief overall assessment (1-2 sentences)
               - List key findings as concise bullet points
               - Hide verbose explanations in collapsible sections
               - Use emoji sparingly for visual clarity: (good), (warning), (issue), (suggestion)

            Example format:
            ```markdown
            ## Claude Code Review Summary

            **Last updated:** [timestamp]
            **Commit:** [sha]

            Overall assessment in one sentence.

            ### Key Findings:
            - Brief point about what's good
            - Brief concern that needs attention
            - Brief suggestion for improvement

            <details>
            <summary>Detailed Analysis</summary>

            Extended explanations, code examples, and detailed reasoning go here...

            </details>

            <details>
            <summary>Additional Considerations</summary>

            Any other detailed thoughts, edge cases, or extensive recommendations...

            </details>
            ```

            Remember: Developers should be able to quickly scan your review and dive into details only when needed.

            1. Check for existing summary comment:
               ```bash
               existing_summary=$(gh api "/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number || github.event.issue.number }}/comments" | \
                 jq -r '.[] | select(.body | startswith("## Claude Code Review Summary")) | .id' | head -1)
               ```

            2. If summary exists, UPDATE it:
               ```bash
               gh api -X PATCH "/repos/${{ github.repository }}/issues/comments/${existing_summary}" \
                 -f body="## Claude Code Review Summary

               **Last updated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
               **Commit:** ${{ steps.pr-sha.outputs.sha }}

               [Your comprehensive review here]"
               ```

            3. If no summary exists, CREATE it:
               ```bash
               gh pr comment ${{ github.event.pull_request.number || github.event.issue.number }} \
                 --body "## Claude Code Review Summary

               **Last updated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
               **Commit:** ${{ steps.pr-sha.outputs.sha }}

               [Your comprehensive review here]"
               ```

            ## For Comment Events (when mentioned):

            ${{ github.event_name == 'issue_comment' && 'Someone mentioned Claude (case-insensitive). Create a NEW reply comment (do not edit existing comments):' || '' }}

            ```bash
            # Always create a new reply
            gh pr comment ${{ github.event.issue.number }} \
              --body "## Claude Reply

            @${{ github.event.comment.user.login }} [Your helpful response to their question/comment]

            ---
            *Responding to: [comment](${{ github.event.comment.html_url }})*"
            ```

            Remember:
            - ONE summary comment per PR (always edit/update it)
            - Multiple reply comments allowed (always create new ones)
            - Be constructive and helpful in all feedback

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*),Bash(gh api:*),Bash(jq:*),Bash(head:*),Bash(date:*),Bash(echo:*),Bash(test:*)"'
